version: "3.9"

services:
  flask_app:
    image: danielavidov/nginx-test-daniel-new:flask_app
    volumes:
     -  /var/run/docker.sock:/var/run/docker.sock
    networks:
      - albit_test

  nginx_revers_proxy:
    image: danielavidov/nginx-test-daniel-new:nginx_proxy
    ports: 
      - 127.0.0.1:80:80
    networks:
      - albit_test

networks:
    albit_test:
      driver: bridge



